allow-branch = [
    "*",
    "!HEAD",
]
sign-commit = false
sign-tag = false
push-remote = "origin"
release = false
publish = false
verify = true
owners = []
push = true
push-options = []
consolidate-commits = false
pre-release-commit-message = "chore: Release {{crate_name}} version {{version}}"
pre-release-replacements = []
tag-message = "chore: Release {{crate_name}} version {{version}}"
tag-name = "{{prefix}}v{{version}}"
tag = true
enable-features = []
enable-all-features = false
dependent-version = "upgrade"
metadata = "optional"
certs-source = "webpki"

[unstable]
workspace-publish = false

[rate-limit]
new-packages = 5
existing-packages = 30
