[package]
name = "runway_selector_core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Area-agnostic runway-selection logic for es_runway_selector"

[dependencies]
askama = { workspace = true }
encoding = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
jiff = { workspace = true }
metar_decoder = { workspace = true }
nom = { workspace = true }
open = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
runway_plugin_api = { workspace = true }
runway_selector_area_config = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-unwrap = { workspace = true }
vatsim_utils = { workspace = true }

[dev-dependencies]
