[package]
name = "es_runway_selector"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
dialoguer = { workspace = true }
directories = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
jiff = { workspace = true }
regex = { workspace = true }
runway_plugin_api = { workspace = true }
runway_selector_area_config = { workspace = true }
runway_selector_areas = { workspace = true }
runway_selector_core = { workspace = true }
runway_selector_plugin_host = { workspace = true }
semver = { workspace = true }
self_update = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
sysinfo = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true, features = ["preserve_order"] }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-unwrap = { workspace = true }
walkdir = { workspace = true }
whoami = { workspace = true }

[target.'cfg(not(target_env = "musl"))'.dependencies]
rfd = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
